name: Java CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Create output directory
      run: mkdir bin

    - name: Copy Resources
      run: |
        xcopy /s /e /i /y data bin\data
        xcopy /s /e /i /y images bin\images

    - name: Compile Source Code
      run: |
        dir /s /b src\*.java > sources.txt
        javac -d bin -cp "lib\*" -encoding UTF-8 @sources.txt

    - name: Compile Test Code
      run: |
        dir /s /b test\*.java > test_sources.txt
        javac -d bin -cp "bin;lib\*" -encoding UTF-8 @test_sources.txt

    - name: Run Tests
      run: |
        java -cp ".;lib\junit-platform-console-standalone-1.10.2.jar;bin;lib\*" org.junit.platform.console.ConsoleLauncher --scan-classpath=bin --reports-dir=test-results
